import { Capabilities } from '../interfaces/Capabilities';

export class AssetCapabilities {
    flagHasEcostart?: boolean;
    flagHasTimeSync?: boolean;
    flagHasChrono?: boolean;
    flagHasPower?: boolean;
    flagHasSetpoint?: boolean;
    flagHasSwitchOnOff?: boolean;
    flagErrorStatus?: boolean;
    flagHasSwitchOnMultifirePellet?: boolean;
    flagIsAir?: boolean;
    flagIsHydro?: boolean;
    flagHasFan?: boolean;
    valueFanFunctionFirst?: number;
    flagHasFanZeroSpeedFan?: boolean;
    flagHasFanModeAuto?: boolean;
    flagHasFanModeHigh?: boolean;
    flagHasFanModeProp?: boolean;
    flagHasFanMain?: boolean;
    flagHasFanSecond?: boolean;
    flagHasFanThird?: boolean;
    flagHasPelletSensorLeveltronic?: boolean;
    flagHasPelletSensorCapacitive?: boolean;
    valueLeveltronicMin?: number;
    valueLeveltronicTreshold?: number;
    valueLeveltronicLevel?: number;
    flagHasTempCombustion?: boolean;
    flagHasDoorControl?: boolean;
    flagHasLightControl?: boolean;
    valueProductType?: number;
    valueProductIsOn?: number;
    valueTempAirDescription?: number;
    valueTempHydroDescription?: number;
    valueTempHydroT1Description?: number;
    valueTempMain?: number;
    valueTempMainDescription?: number;
    valueTempHydroT1?: number;
    valueTempHydroT2?: number;
    valueTempWoodCombustion?: number;
    valuePowerCurrent?: number;
    valueSetpointMin?: number;
    valueSetpointMax?: number;
    valueSetpoint?: number;
    valuePower?: number;
    valueFanMain?: number;
    valueFanSecond?: number;
    valueFanThird?: number;
    valueFanLimits?: number[];
    valueDoorStatus?: number;
    valueLightStatus?: number;

    constructor(capabilities: Capabilities) {
        this.flagHasEcostart = capabilities?.flag_modalita_ecostart ?? false;
        this.flagHasTimeSync = capabilities?.flag_sincronizzazione_orario ?? false;
        this.flagHasChrono = capabilities?.flag_presenza_chrono ?? false;
        this.flagHasPower = !(capabilities?.flag_assenza_regolazione_potenza ?? false) ? true : false;
        this.flagHasSetpoint = capabilities?.flag_impostazione_setpoint ?? false;
        this.flagHasSwitchOnOff = capabilities?.flag_accensione_macchina ?? false;
        this.flagErrorStatus = capabilities?.flag_presenza_errore_macchina ?? false;
        this.flagHasSwitchOnMultifirePellet = capabilities?.flag_prenotazione_accensione_pellet ?? false;
        this.flagIsAir = capabilities?.flag_tipologia_aria ?? false;
        this.flagIsHydro = capabilities?.flag_tipologia_idro ?? false;
        this.flagHasFan = capabilities?.flag_presenza_ventilatore ?? false;
        this.valueFanFunctionFirst = capabilities?.value_fan_function_first ?? undefined;
        this.flagHasFanZeroSpeedFan = capabilities?.flag_presenza_zero_speed_fan ?? false;
        this.flagHasFanModeAuto = capabilities?.flag_presenza_ventilatore_mod_auto ?? false;
        this.flagHasFanModeHigh = capabilities?.flag_presenza_ventilatore_mod_high ?? false;
        this.flagHasFanModeProp = capabilities?.flag_presenza_ventilatore_mod_prop ?? false;
        this.flagHasFanMain = capabilities?.flag_presenza_primo_ventilatore ?? false;
        this.flagHasFanSecond = capabilities?.flag_presenza_secondo_ventilatore ?? false;
        this.flagHasFanThird = capabilities?.flag_presenza_terzo_ventilatore ?? false;
        this.flagHasPelletSensorLeveltronic = capabilities?.flag_presenza_sensore_pellet_leveltronic ?? false;
        this.flagHasPelletSensorCapacitive = capabilities?.flag_presenza_sensore_pellet_capacitivo ?? false;
        this.valueLeveltronicMin = capabilities?.value_leveltronic_minimo ?? undefined;
        this.valueLeveltronicTreshold = capabilities?.value_leveltronic_soglia ?? undefined;
        this.valueLeveltronicLevel = capabilities?.value_leveltronic_level ?? undefined;
        this.flagHasTempCombustion = capabilities?.flag_presenza_temperatura_combustione ?? false;
        this.flagHasDoorControl = capabilities?.flag_presenza_porta ?? false;
        this.flagHasLightControl = capabilities?.flag_presenza_luci ?? false;
        this.valueProductType = capabilities?.value_tipologia_macchina ?? undefined;
        this.valueProductIsOn = capabilities?.value_accensione_macchina ?? undefined;
        this.valueTempAirDescription = capabilities?.value_descrizione_temperatura_aria ?? undefined;
        this.valueTempHydroDescription = capabilities?.value_descrizione_temperatura_idro ?? undefined;
        this.valueTempHydroT1Description = capabilities?.value_descrizione_sonda_t1_idro ?? undefined;
        this.valueTempMain = capabilities?.value_temperatura_sonda_principale ?? undefined;
        this.valueTempMainDescription = capabilities?.value_descrizione_sonda_principale ?? undefined;
        this.valueTempHydroT1 = capabilities?.value_temperatura_sonda_t1_idro ?? undefined;
        this.valueTempHydroT2 = capabilities?.value_temperatura_sonda_t2_idro ?? undefined;
        this.valueTempWoodCombustion = capabilities?.value_temperatura_sonda_combustione_legna ?? undefined;
        this.valuePowerCurrent = capabilities?.value_power_rilevato ?? undefined;
        this.valueSetpointMin = capabilities?.value_setpoint_minimo ?? undefined;
        this.valueSetpointMax = capabilities?.value_setpoint_massimo ?? undefined;
        this.valueSetpoint = capabilities?.value_setpoint_impostato ?? undefined;
        this.valuePower = capabilities?.value_power_impostato ?? undefined;
        this.valueFanMain = capabilities?.value_fan_first ?? undefined;
        this.valueFanSecond = capabilities?.value_fan_second ?? undefined;
        this.valueFanThird = capabilities?.value_fan_third ?? undefined;
        this.valueFanLimits = capabilities?.value_fan_limits ?? undefined;
        this.valueDoorStatus = capabilities?.value_apertura_porta ?? undefined;
        this.valueLightStatus = capabilities?.value_accensione_luce ?? undefined;
    }
}
